export const POSTGRES_CA = process.env.POSTGRES_CA
export const SERVER_URL = process.env.SERVER_URL

const children = [
  {
    id: 1,
    name: '고현준',
    age: 15,
  },
  {
    id: 2,
    name: '곽태욱',
    age: 15,
  },
  {
    id: 3,
    name: '이수민',
    age: 13,
  },
  {
    id: 4,
    name: '김도윤',
    age: 11,
  },
  {
    id: 5,
    name: '박서준',
    age: 12,
  },
  {
    id: 6,
    name: '이하준',
    age: 13,
  },
  {
    id: 7,
    name: '이서아',
    age: 14,
  },
  {
    id: 8,
    name: '김하윤',
    age: 15,
  },
  {
    id: 9,
    name: '박지안',
    age: 16,
  },
  {
    id: 10,
    name: '유아린',
    age: 9,
  },
]

export const fundings = [
  {
    id: 1,
    title: '변신 로보트를 가지고 싶은 15살 현준 어린이',
    imageUrl: '/images/1.png',
    story:
      '안녕하세요 저는 15살 고현준입니다. 저는 올해 정말 착하게 지냈습니다. 방 청소를 스스로 했고, 설거지도 했어요. 저는 크리스마스 선물로 변신 로보트 장난감을 받고 싶어요!',
    price: 200_000,
    present_image_url: '/images/01.png',
    present_name: '변신 로보트',
    child: children[0],
  },
  {
    id: 2,
    title: '레고 장난감을 가지고 싶은 15살 태욱 어린이',
    imageUrl: '/images/2.png',
    story:
      '안녕하세요? 저는 15살 곽태욱입니다. 선생님 말 잘 듣는 착한 어린이에요. 크리스마스 선물로 멋있는 레고 장난감을 받고싶어요. 다들 감사합니다.',
    price: 100_000,
    present_image_url: '/images/02.png',
    present_name: '곰돌이',
    progress: 14,
    child: children[1],
  },
  {
    id: 3,
    title: '아이폰을 가지고 싶은 13살 수민 어린이',
    imageUrl: '/images/3.png',
    story: '',
    price: 1_400_000,
    present_image_url: '/images/03.png',
    present_name: '다꾸 세트',
    progress: 11,
    child: children[2],
  },
  {
    id: 4,
    title: '에어팟 2세대를 가지고 싶은 15살 현준 어린이',
    imageUrl: '/images/4.png',
    story: '',
    price: 300_000,
    present_image_url: '/images/04.png',
    present_name: '스탬프 놀이북',
    progress: 36,
    child: children[0],
  },
  {
    id: 5,
    title: '에어팟 2세대를 가지고 싶은 15살 현준 어린이',
    imageUrl: '/images/5.jpeg',
    story: '',
    price: 300_000,
    present_image_url: '/images/05.png',
    present_name: '레고 자동차',
    progress: 34,
    child: children[3],
  },
  {
    id: 6,
    title: '에어팟 2세대를 가지고 싶은 15살 현준 어린이',
    imageUrl: '/images/6.jpeg',
    story: '',
    price: 300_000,
    present_image_url: '/images/06.png',
    present_name: '에어팟 2세대',
    progress: 45,
    child: children[4],
  },
  {
    id: 7,
    title: '에어팟 2세대를 가지고 싶은 15살 현준 어린이',
    imageUrl: '/images/7.webp',
    story: '',
    price: 300_000,
    present_image_url: '/images/07.png',
    present_name: '곰돌이 인형',
    progress: 87,
    child: children[5],
  },
  {
    id: 8,
    title: '에어팟 2세대를 가지고 싶은 15살 현준 어린이',
    imageUrl: '/images/8.jpeg',
    story: '',
    price: 300_000,
    present_image_url: '',
    present_name: '에어팟 2세대',
    progress: 23,
    child: children[6],
  },
  {
    id: 9,
    title: '에어팟 2세대를 가지고 싶은 15살 현준 어린이',
    imageUrl: '/images/9.jpeg',
    story: '',
    price: 300_000,
    present_image_url: '',
    present_name: '에어팟 2세대',
    progress: 75,
    child: children[7],
  },
  {
    id: 10,
    title: '에어팟 2세대를 가지고 싶은 15살 현준 어린이',
    imageUrl: '',
    story: '',
    price: 300_000,
    present_image_url: '',
    present_name: '에어팟 2세대',
    child: children[8],
  },
  {
    id: 11,
    title: '에어팟 2세대를 가지고 싶은 15살 현준 어린이',
    imageUrl: '',
    story: '',
    price: 300_000,
    present_image_url: '',
    present_name: '에어팟 2세대',
    child: children[9],
  },
]
